### ISSUE TITLE
Calling the qwen-vl-max-latest model to analyze images, streaming output, resulting in a NullPointerException

### ISSUE THREAD

**Issue by strikerzhu** [alibaba/spring-ai-alibaba#141]
**Which Component**
ChatModel

**Describe the bug**
Calling the qwen-vl-max-latest model to analyze images, streaming output, resulting in a NullPointerException.
"com.alibaba.cloud.ai.dashscope.api.DashScopeApi$TokenUsage.totalTokens()" is null

The error message is as follows:

org.springframework.ai.chat.model.MessageAggregator [171] [] [] ERROR Aggregation Error
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.longValue()" because the return value of "com.alibaba.cloud.ai.dashscope.api.DashScopeApi$TokenUsage.totalTokens()" is null
	at com.alibaba.cloud.ai.dashscope.metadata.DashScopeAiUsage.getTotalTokens(DashScopeAiUsage.java:56)
DashScopeAiUsage.java:56
	at org.springframework.ai.chat.model.MessageAggregator.lambda$aggregate$4(MessageAggregator.java:126)
MessageAggregator.java:126
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:196)
FluxPeekFuseable.java:196
	

**Simplest demo**
The URL of the simplest demo to reproduce the problem.

        URL imageUrl = ...
        List<Media> mediaList = List.of(new Media(MimeTypeUtils.IMAGE_PNG, imageUrl));
        UserMessage userMessage = new UserMessage("", mediaList);
        userMessage.getMetadata().put(DashScopeChatModel.MESSAGE_FORMAT, MessageFormat.IMAGE);

        Message systemMessage = new SystemMessage("这些是什么?");
        Prompt prompt = new Prompt(
            List.of(systemMessage, userMessage),
            DashScopeChatOptions.builder()
                            .withModel("qwen-vl-max-latest")
                            .withTemperature(1.3)
                            .withMultiModel(true)
                            .withStream(true)
                            .build()
        );
        Flux<ChatResponse> chatResponseFlux = chatModel.stream(prompt);
        List<ChatResponse> responses = chatResponseFlux.collectList().block();

NullPointerException comes out from the last line.

**To Reproduce**
run the up code

**Expected behavior**
No exception.
If I use chatModel.call there is no problem.

**Screenshots**

**Additional context**
 MacOS  、Java21、SpringBoot 3.3.6

**Comment by ZeroVd** [comment]
The return structure of usage in DashScopeApi is different from our defined usage, which causes non-plain-text calls to be incorrectly mapped.
![be1458f33abc7b2df34e9d37805c1cef](https://github.com/user-attachments/assets/32091430-a5db-4316-a469-08b278f25535)
![f260b0f1ea42fb6f88863cdd1446a39f](https://github.com/user-attachments/assets/d0deceb5-6d54-4e96-adbf-92f942926fb6)
![8957f3ca4986806640c2b0b9937016ee](https://github.com/user-attachments/assets/79de43e7-1e56-4fad-9f84-9d6a34e09d1b)

The error during streaming occurs because usage.getTotalTokens() is used in MessageAggregator. For non-streaming calls, the return is the same, but since getTotalTokens is not called, there is no NPE. However, when we actually call this method, it still throws an NPE.

I will provide a fixed version. Thank you for your feedback.
